baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'gokarna'

[params]
  footer = "The Marauders"
  description = "Sky above, sand below and peace within"
  avatarURL = "/images/avatar_pixelated.png"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  socialIcons = [
    {name = "twitter", url = "https://example.com"},
    {name = "linkedin", url = "https://example.com"},
    {name = "stackoverflow", url = "https://example.com"},
    {name = "dribbble", url = "https://example.com"},
    {name = "instagram", url = "https://example.com"},
    {name = "twitch", url = "https://example.com"},
    {name = "email", url = "mailto:example@example.com"},
    {name = "mastodon", url = "mailto:example@example.com"}
  ]
