baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'gokarna'

[params]
  footer = "The Marauders"
  description = "Sky above, sand below and peace within"
  avatarURL = "/images/avatar_pixelated.png"
  AvatarAltText = "avatar"
  avatarSize = "size-m"