baseURL = 'https://federico.travaini.xyz'
languageCode = 'en-us'
title = 'Federico Travaini | ftrava'
theme = 'gokarna'
disableKinds = ['taxonomy', 'term']

[params]
  footer = "Federico Travaini (ftrava)"
  description = "Mechanical engineer, automation enthusiast, self-hosting geek, and podcaster since 2010."
  avatarURL = "/images/avatar_pixelated.png"
  AvatarAltText = "Federico Travaini avatar"
  avatarSize = "size-m"
  socialIcons = [
    {name = "email", url = "mailto:federico@travaini.xyz"},
    {name = "website", url = "https://pompetravaini.com"},
    {name = "easyapple", url = "http://itunes.apple.com/it/podcast/easyapple/id523499126"},
    {name = "linkedin", url = "https://www.linkedin.com/in/federico-travaini/"},
    {name = "twitter", url = "https://x.com/ftrava"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
